### ISSUE TITLE
What's the status of this proposal?

### ISSUE THREAD

**Issue by lambda-fairy** [kennytm/thin_cstr#1]
I was researching `CStr` and ended up here. It looks pretty fleshed out to me, so I'm wondering what is happening with it now :slightly_smiling_face:

**Comment by kennytm** [comment]
Well the problem is we can't have a proper `size_of_val` of an `extern type` (rust-lang/rust#49708, rust-lang/rust#43467), and because `size_of_val` of an `extern type` doesn't behave correctly when treated as a `CStr`, a `Box<CStr>` will not work either (`size_of_val` returning 0 means freeing the box will leak the string, aborting means... aborting). 

We'll need proper custom DST support unfortunately. rust-lang/rfcs#2580 and rust-lang/rfcs#2594 are the first steps.
